blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/CreativeCodingSolutions/docucraft/discussions
    about: Please use GitHub Discussions for questions and discussions.
