function categorizeFiles(files) {
  const cats = { source: [], config: [], test: [], docs: [], asset: [], other: [] };
  for (const f of files) {
    const ext = f.split(".").pop().toLowerCase();
    if (["ts","tsx","js","jsx","py","rs","go","java","rb","php","c","cpp","h","hpp","swift","kt","scala"].includes(ext)) {
      if (/test|spec|__tests__/.test(f)) cats.test.push(f);
      else cats.source.push(f);
    } else if (["json","yaml","yml","toml","ini","cfg","env","conf"].includes(ext)) {
      cats.config.push(f);
    } else if (["md","rst","txt","adoc","wiki"].includes(ext)) {
      cats.docs.push(f);
    } else if (["svg","png","jpg","jpeg","gif","ico","woff","woff2","ttf","eot","css","scss","less"].includes(ext)) {
      cats.asset.push(f);
    } else {
      cats.other.push(f);
    }
  }
  return cats;
}

export function generateDescription({ prTitle, diff, files, fileDetails, style }) {
  const cats = categorizeFiles(files);
  const fileCount = files.length;

  const hasSource = cats.source.length > 0;
  const hasConfig = cats.config.length > 0;
  const hasTest = cats.test.length > 0;
  const hasDocs = cats.docs.length > 0;
  const hasAsset = cats.asset.length > 0;
  const hasOther = cats.other.length > 0;

  let summary = `This pull request modifies ${fileCount} file`;
  if (fileCount !== 1) summary += "s";
  summary += ".";
  const parts = [];
  if (hasSource) parts.push("Includes source code changes.");
  if (hasTest) parts.push("Includes test updates.");
  if (hasConfig) parts.push("Includes configuration changes.");
  if (parts.length) summary += " " + parts.join(" ");

  let changesSection = "";
  const appendCat = (label, items) => {
    if (items.length) {
      changesSection += `\n### ${label}\n\n`;
      changesSection += items.map(i => `- ${i}`).join("\n") + "\n";
    }
  };
  if (hasSource) appendCat("Source Code", cats.source);
  if (hasConfig) appendCat("Configuration", cats.config);
  if (hasTest) appendCat("Tests", cats.test);
  if (hasDocs) appendCat("Documentation", cats.docs);
  if (hasAsset) appendCat("Assets", cats.asset);
  if (hasOther) appendCat("Other Changes", cats.other);

  const footer = "\n\n---\n\n###### 🤖 Generated by [DocuCraft](https://github.com/CreativeCodingSolutions/docucraft)";

  if (style === "summary-only") {
    return `## Summary\n\n${summary}${footer}`;
  }

  if (style === "minimal") {
    return `## Summary\n\n${summary}\n\n### Files Changed\n\n${files.map(f => `- ${f}`).join("\n")}${footer}`;
  }

  if (style === "detailed") {
    const preview = diff ? `\n### Diff Preview\n\n\`\`\`diff\n${diff.slice(0, 3000)}\n\`\`\`\n` : "";
    return `## Summary\n\n${summary}\n\n### Changes by Category${changesSection}\n${preview}\n### Why\n\nAutomated pull request description generated by DocuCraft. See diff preview above for detailed changes.${footer}`;
  }

  return `## Summary\n\n${summary}\n\n### Changes by Category${changesSection}\n\n### Why\n\nAutomated pull request description generated by DocuCraft. Review the diff for detailed changes.${footer}`;
}
