import { createAppAuth } from "@octokit/auth-app";
import { request } from "@octokit/request";
import express from "express";
import crypto from "node:crypto";
import { generateDescription } from "./generate.js";

const app = express();
app.use(express.json({ verify: (req, _res, buf) => { req.rawBody = buf; } }));

async function getInstallationToken(appId, privateKey, installationId) {
  const auth = createAppAuth({ appId, privateKey, installationId });
  const { token } = await auth({ type: "installation" });
  return token;
}

async function updatePrDescription(token, owner, repo, prNumber, description) {
  await request("PATCH /repos/{owner}/{repo}/pulls/{pull_number}", {
    owner, repo, pull_number: prNumber,
    body: description,
    headers: { authorization: `Bearer ${token}` },
  });
}

async function postViralComment(token, owner, repo, prNumber) {
  const existing = await request("GET /repos/{owner}/{repo}/issues/{issue_number}/comments", {
    owner, repo, issue_number: prNumber,
    headers: { authorization: `Bearer ${token}` },
  });
  if (existing.data.some(c => c.body?.includes("DocuCraft"))) return;

  await request("POST /repos/{owner}/{repo}/issues/{issue_number}/comments", {
    owner, repo, issue_number: prNumber,
    body: [
      "> 📝 PR description auto-generated by [DocuCraft](https://github.com/CreativeCodingSolutions/docucraft)",
      ">",
      "> Add DocuCraft to your repo — install the GitHub App:",
      "> [![Install DocuCraft](https://img.shields.io/badge/Install-GitHub_App-2ea44f?style=flat-square)](https://github.com/apps/docucraft)",
      ">",
      "> _Works on every PR. One-click install. Zero config._",
    ].join("\n"),
    headers: { authorization: `Bearer ${token}` },
  });
}

async function getPrDiff(token, owner, repo, prNumber) {
  const res = await request("GET /repos/{owner}/{repo}/pulls/{pull_number}", {
    owner, repo, pull_number: prNumber,
    mediaType: { format: "diff" },
    headers: { authorization: `Bearer ${token}` },
  });
  return res.data;
}

async function getPrFiles(token, owner, repo, prNumber) {
  const res = await request("GET /repos/{owner}/{repo}/pulls/{pull_number}/files", {
    owner, repo, pull_number: prNumber,
    headers: { authorization: `Bearer ${token}` },
  });
  return res.data;
}

function verifyWebhook(payload, signature, secret) {
  const sig = `sha256=${crypto.createHmac("sha256", secret).update(payload).digest("hex")}`;
  return crypto.timingSafeEqual(Buffer.from(sig), Buffer.from(signature));
}

app.post("/webhook", async (req, res) => {
  const sig = req.headers["x-hub-signature-256"];
  if (sig && !verifyWebhook(req.rawBody, sig, process.env.GITHUB_APP_WEBHOOK_SECRET)) {
    return res.status(401).json({ error: "Invalid signature" });
  }

  const event = req.headers["x-github-event"];
  if (event !== "pull_request") return res.status(200).json({ ok: true });
  if (req.body.action !== "opened") return res.status(200).json({ ok: true });

  const { repository, installation, pull_request: pr } = req.body;
  if (!installation) return res.status(200).json({ ok: true });

  const [owner, repo] = repository.full_name.split("/");
  if (!owner || !repo) return res.status(400).json({ error: "Missing owner/repo" });

  try {
    const token = await getInstallationToken(
      process.env.GITHUB_APP_ID,
      process.env.GITHUB_APP_PRIVATE_KEY.replace(/\\n/g, "\n"),
      installation.id
    );

    const [diff, files] = await Promise.all([
      getPrDiff(token, owner, repo, pr.number),
      getPrFiles(token, owner, repo, pr.number),
    ]);

    const description = generateDescription({
      prTitle: pr.title,
      diff: diff.slice(0, 32000),
      files: files.map(f => f.filename),
      fileDetails: files.map(f => ({
        path: f.filename, status: f.status,
        additions: f.additions, deletions: f.deletions,
      })),
      style: "standard",
    });

    await Promise.all([
      updatePrDescription(token, owner, repo, pr.number, description),
      postViralComment(token, owner, repo, pr.number),
    ]);

    res.json({ ok: true, pr: pr.number });
  } catch (err) {
    console.error("Webhook error:", err);
    res.status(500).json({ error: err.message });
  }
});

app.get("/health", (_req, res) => res.json({ status: "ok" }));

const port = process.env.PORT || 3000;
app.listen(port, () => console.log(`DocuCraft webhook server running on :${port}`));
